Создание миграций
dimonk33/sql-migrator pull request #1
Opened 2023-05-15 07:00 UTC by dimonk33

1) CLI функционал
2) Передача настроек
3) Реализация команды создания миграции

2023-05-18 18:48 UTC, dshemin requested changes

2023-05-18 18:48 UTC, dshemin commented on internal/cmd/root.go
> +	// Путь до миграций по умолчанию.
Важно:

Обратите внимание на комментарии, они дублируются.

2023-05-18 18:48 UTC, dshemin commented on internal/cmd/create.go
> +const ErrCreatePrefix = "создание миграции: "
Важно:

Данная константа не должна быть экспортируемой. Более того, она используется только в одной функции и поэтому её следует определить только в этой функции.

Похожие константы есть и в других командах, там тоже надо поправить.

2023-05-18 18:48 UTC, dshemin commented on internal/cmd/status.go
> +		err = m.Create(args[0], migrateType)
Важно:

Не верная функция вызывается.

2023-05-18 18:48 UTC, dshemin commented on internal/db/pg.go
> +		return err
Критично:

Тут мы выходим, а кто и когда заролбечит транзакцию которую мы тут начали?

2023-05-18 18:48 UTC, dshemin commented on internal/db/pg.go
> +		return false
Критично:

А что если проблема с соединением БД? Очень опрометчиво решать что если у нас ошибка то мы не можем залочить.

2023-05-18 18:48 UTC, dshemin commented on internal/db/pg.go
> +		_ = tx.Rollback()
Важно:

Игнорирование ошибок быть не должно. Хотя бы залогируйте иначе потом можно потратить часы пытаясь понять что не так.

2023-05-18 18:48 UTC, dshemin commented on pkg/gomigrator/migrator.go
> +	migrateType = strings.ToLower(strings.Trim(migrateType, " \t\r\n"))
Важно:

Есть https://pkg.go.dev/strings#TrimSpace

2023-05-25 17:10 UTC, dshemin approved these changes

2023-05-25 17:10 UTC, dshemin commented on internal/cmd/root.go
> +	// Путь до миграций по умолчанию.
Важно:

И всё таки это не `Путь до миграций по умолчанию.` а скорее `Тип миграции по умолчанию`.

2023-05-25 17:10 UTC, dshemin commented on pkg/gomigrator/migrator.go
> +func (mt MigrateType) String() string {
Важно:

Можно вместо нового типа сделать алиас и тогда не понадобится этот метод.

2023-05-25 22:41 UTC, dimonk33 commented
Результат интеграционных тестов
[+] Running 3/3
 ✔ Network deployments_migrator-network  Created                                                                                                                                                                                  0.1s 
 ✔ Container migrator-postgres           Healthy                                                                                                                                                                                 11.5s 
 ✔ Container integration_tests           Started                                                                                                                                                                                 12.0s 
[+] Running 1/0
 ✔ Container migrator-postgres  Running                                                                                                                                                                                           0.0s 
INFO    2023/05/25 22:33:28 Cписок миграций:
 map[111111_sql_migration.sql:/go/src/migrations/111111_sql_migration.sql 222222_go_migration.go:/go/src/migrations/222222_go_migration.go]
INFO    2023/05/25 22:33:28 Cписок миграций для применения:
 map[111111_sql_migration.sql:/go/src/migrations/111111_sql_migration.sql 222222_go_migration.go:/go/src/migrations/222222_go_migration.go]
INFO    2023/05/25 22:33:28 Применение миграции 111111_sql_migration.sql
INFO    2023/05/25 22:33:28 Миграция /go/src/migrations/111111_sql_migration.sql применена
INFO    2023/05/25 22:33:28 Применение миграции 222222_go_migration.go
INFO    2023/05/25 22:33:30 удаление каталога миграции: <nil>
INFO    2023/05/25 22:33:30 Миграция /go/src/migrations/222222_go_migration.go применена
INFO    2023/05/25 22:33:35 Cписок миграций:
 map[111111_sql_migration.sql:/go/src/migrations/111111_sql_migration.sql 222222_go_migration.go:/go/src/migrations/222222_go_migration.go]
INFO    2023/05/25 22:33:37 Откат миграции 222222_go_migration.go
INFO    2023/05/25 22:33:38 удаление каталога миграции: <nil>
INFO    2023/05/25 22:33:38 Миграция 222222_go_migration.go отменена
INFO    2023/05/25 22:33:38 Cписок миграций:
 map[111111_sql_migration.sql:/go/src/migrations/111111_sql_migration.sql 222222_go_migration.go:/go/src/migrations/222222_go_migration.go]
INFO    2023/05/25 22:33:38 Откат миграции 111111_sql_migration.sql
INFO    2023/05/25 22:33:38 Миграция 111111_sql_migration.sql отменена
PASS
ok      github.com/dimonk33/sql-migrator        9.821s
[+] Running 3/3
 ✔ Container integration_tests           Removed                                                                                                                                                                                  0.0s 
 ✔ Container migrator-postgres           Removed                                                                                                                                                                                  0.5s 
 ✔ Network deployments_migrator-network  Removed

2023-05-26 16:53 UTC, dshemin approved these changes

2023-05-30 17:02 UTC, merged